logs:
 - name: root
   level: info
   fomartter: "%d%T%m%n" 
   appender:
      - type: FileLogAppender
        file: log.txt
      - type: StdoutLogAppender

 - name: system
   level: debug
   fomartter: "%d%T%m%n"
   appender:
      - type: FileLogAppender
        file: log.txt
      - type: StdoutLogAppender

system:
   port: 9900
   value: 15
   int_vec: 
    - 10
    - 20
   list_vec: 
    - 30
    - 40