logs:
 - name: root
   level: info
   fomartter: "%d%T%m%n" 
   appender:
      - type: FileLogAppender
        file: log.txt
      - type: StdoutLogAppender

 - name: system
   level: debug
   fomartter: "%d%T%m%n"
   appender:
      - type: FileLogAppender
        file: log.txt
      - type: StdoutLogAppender

system:
   port: 9900
   value: 15
   int_vec: 
    - 10
    - 20
   int_list: [30,40]
   int_set: [30,20,40,30]
   int_unset: [30,20,40,30]
   int_map: 
    k: 22
    j: 33
   int_unmap: 
    k: 22
    j: 33
class:
    person:
     name: lubo
     age: 30
     sex: true
    map:
      lubo01:
        name: lubo1
        age: 18
        sex: false
      lubo02:
        name: lubo2
        age: 33
        sex: true
